### PR TITLE
Add spore_sdk test case

### PR DESCRIPTION
**Pull request by Dawn-githup**
# Changes

- Add spore/cluster test case
- Add test workflow for github ci

### CODE REVIEW

**Comment by ashuralyk** [comment]
@Dawn-githup please solve these conflicts

**Comment by Dawn-githup** [comment]
> @Dawn-githup please solve these conflicts

The conflicts have been resolved.

**Comment by ashuralyk** [comment]
@ShookLyngs please pick useful cases from this PR, and then, this PR will be closed when you finished your work

**Comment by ShookLyngs** [comment]
#56 rewrite completed

**Pull request closed without merging**
